### ISSUE TITLE
"Undefined exported function" ERROR

### ISSUE THREAD

**Issue by evan-choi** [lfittl/pg-query-emscripten#7] opened 2020-07-15 10:08 UTC
# How can i build this project successfully ?

#### I tried it to build with the latest source of the libpg_query.

```
make update_source
```

### BUT..

emcc succeeded, but em++ has an error occured.

![error](https://user-images.githubusercontent.com/9690415/87533080-0acda280-c6cf-11ea-9e26-816e7468d577.png)

## Environment

here is my environment

make: GNU Make 3.81
emcc: (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.19
clang: 11.0.0
Target: x86_64-apple-darwin19.5.0

![make-v](https://user-images.githubusercontent.com/9690415/87532428-153b6c80-c6ce-11ea-98a8-75a687f6c49a.png)

![emcc-v](https://user-images.githubusercontent.com/9690415/87532432-166c9980-c6ce-11ea-9d03-ba777f1a34db.png)

**Comment by pthrasher** [comment] 2021-05-03 18:39
I am also getting this error.. Was hoping it is just a quick fix. I tried one thing... but it just gets me to a new but similar error... 
<img width="1388" alt="Screen Shot 2021-05-03 at 2 38 29 PM" src="https://user-images.githubusercontent.com/122682/116917913-4402df00-ac1d-11eb-9ce2-df8e5b3db2d4.png">

<img width="1289" alt="Screen Shot 2021-05-03 at 2 38 58 PM" src="https://user-images.githubusercontent.com/122682/116917964-52e99180-ac1d-11eb-926b-5f0e4b03204f.png">


@lfittl Any chance this is something easy we're just overlooking? There've been a # of breaking changes to emcc since you last committed.

**Comment by lfittl** [comment] 2021-05-03 20:10
@pthrasher Yeah, I think unfortunately this requires a deeper investigation to work out what exactly broke here - as you mention there have been a number of significant changes to emscripten, and these will need to be evaluated in detail.

I currently don't have time to do a deep dive on this unfortunately (there are other higher priority projects), but if you figure out what the problem is, PRs are of course welcome.

**Comment by pthrasher** [comment] 2021-05-04 13:38
@lfittl I understand. I've been digging in... but unfortunately am at the limits of my compiler toolchain knowledge. I'll do some reading and see if I can come up with something. Thanks for the reply!

**Comment by neighbaa** [comment] 2021-05-06 12:58
Funny timing. I had just had a crack at this over the weekend and managed to get libpg_query (10-1.0.2) to build with emsdk (2.0.18). It's working, but with some quirks...

### Changes I made
#### MakeFile:
```
flatten_source: $(LIBDIR)
	mkdir -p obj
	mkdir -p parser
	rm -f parser/*.{c,h}
	rm -fr parser/include
	# Reduce everything down to one directory
	cp -a $(LIBDIR)/src/* parser/
	mv parser/postgres/* parser/
	rmdir parser/postgres
	cp -a $(LIBDIR)/pg_query.h parser/include
# MY FIX BEGINS HERE
	# Make sure every .c file in the top-level directory is its own translation unit
	mv parser/*_conds.c parser/*_defs.c parser/*_helper.c parser/*_random.c parser/include

CC := emcc
CCP := em++
SRC := parser
OBJ := obj

SOURCES := $(wildcard $(SRC)/*.c)
OBJECTS := $(patsubst $(SRC)/%.c, $(OBJ)/%.o, $(SOURCES))

pg_query:$(OBJECTS)
	$(CCP) \
	-I$(SRC)/include \
	-s "ALLOW_MEMORY_GROWTH=1" \
	-s "ASSERTIONS=0" \
	-s EXPORTED_RUNTIME_METHODS="['ALLOC_STACK']" \
	-s "ENVIRONMENT=web" \
	-s "SINGLE_FILE=1" \
	-s "WASM=0" \
	-s "MODULARIZE=1" \
	-s 'EXPORT_NAME="pgQuery"' \
	-s "EXPORT_ES6=1" \
	--memory-init-file 0 \
	-O3 --bind --pre-js module.js \
	$^ entry.cpp -o $@.js

$(OBJ)/%.o: $(SRC)/%.c
	$(CC) -I$(SRC)/include -O3 -c $< -o $@
	
update_source: flatten_source fix_pg_config pg_query
	
# MY FIX ENDS HERE

clean:
	-@ $(RM) -r $(TMPDIR)
```
#### module.js:
```
normalize: function normalize(text) {
    var pointer = allocate(intArrayFromString(text), Module['ALLOC_STACK']);
    ...
  },

  parse: function parse(text) {
    var pointer = allocate(intArrayFromString(text), Module['ALLOC_STACK']);
    ...
  },

  parse_plpgsql: function parse_plpgsql(text) {
    var pointer = allocate(intArrayFromString(text), Module['ALLOC_STACK']);
    ...
  },

  fingerprint: function fingerprint(text) {
    var pointer = allocate(intArrayFromString(text), Module['ALLOC_STACK']);
    ...
  },
```

I then run ```emmake make update_source```

### Some quirks:
 - The first time this runs it fails with missing EXPORT_FUNCTIONS errors, but the second time this runs it succeeds.
 - MODULARIZE was a necessary flag so that the runtime loaded. I'm not savvy enough to know a better way around this. It means that the PgQuery module is now loaded asynchronously at runtime. It's not a problem for me but it deviates from the current usage in that you do something like this to use it in your javascript:
 ```
 import PgQuery from './pg_query';
 (async () => {
        const pgQuery = await PgQuery()
        console.log(pgQuery)
        console.log(pgQuery.parse("SELECT 1"));
  })()
 ```

#### libpg_query 13-2.0.4
I  also tried to build 13-2.0.4 and managed to get somewhere with it, but ran into compile issues in the source code.
The fix here was identical except I added another rule move_extra:
```
move_extra:
	mkdir -p parser/include/protobuf
	mkdir -p parser/include/protobuf-c
	mkdir -p parser/include/xxhash
	cp -a tmp/libpg_query/protobuf* parser/include
	cp -a tmp/libpg_query/vendor/protobuf-c* parser/include
	cp -a tmp/libpg_query/vendor/xxhash* parser/include
```
which is then called in update_source:
```update_source: flatten_source fix_pg_config move_extra pg_query```
	
I'm quite new to C/C++, MakeFiles and Emscripten, so there's likely a bunch wrong with this, but hopefully this is helpful if anyone is looking at porting the latest (13-2.0.4).

I'm using Ubuntu-20.04 in Windows WSL2.

**Comment by pthrasher** [comment] 2021-05-06 14:25
> The first time this runs it fails with missing EXPORT_FUNCTIONS errors, but the second time this runs it succeeds.

Sounds like some kind of compile-order problem.

> MODULARIZE was a necessary flag so that the runtime loaded. I'm not savvy enough to know a better way around this. It means that the PgQuery module is now loaded asynchronously at runtime. It's not a problem for me but it deviates from the current usage in that you do something like this to use it in your javascript

There are some other settings... I wonder if there's a way to enable the runtime but not do async.

**Comment by neighbaa** [comment] 2021-05-06 15:10
> Sounds like some kind of compile-order problem.

I figure that but not sure how to order it.

> There are some other settings... I wonder if there's a way to enable the runtime but not do async.

I tried all of these and could only get the last one to work: https://emscripten.org/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions

**Closed as not planned** 2024-03-06 01:24 UTC
